#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

ENV_FILE="/private/tmp/dino-crm-wiring.env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"

banner "CRM-Verdrahtung 03 · Abnahme gegen den Codebefund"

_die() { warn "$1"; exit 1; }

_need() {
  local v
  v=$(_existing "$1" || true)
  [[ -n "$v" ]] || _die "Es fehlt $1. Zuerst Wizard 01, dann Mapping."
  printf '%s' "$v"
}

_append_note() {
  local title="$1" body="$2"
  {
    printf '\n## Wizard-03 %s\n\n' "$title"
    printf '%s\n' "$body"
  } >> "$WORK_MD"
}

ask_jno() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps %s]%s ' "$BOLD" "$prompt [ja/nein/OFFEN]" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt [ja/nein/OFFEN]" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  [[ -z "$input" ]] && input="OFFEN"
  printf -v "$key" '%s' "$input"
}

stage "Was dieser Wizard ist"
WORK_MD=$(_need WORK_MD)
[[ -f "$WORK_MD" ]] || _die "Arbeitsdatei weg: $WORK_MD"
say "Quelle ist NICHT hits-rpc/tables/ui.txt. Das sind nur Suchzettel."
say "Quelle ist die Verdrahtungsdatei mit dem Codebefund."
note "$WORK_MD"
say "Du bestaetigst oder widersprichst. Leer = OFFEN. Kein MCP, keine DB."
if command -v open >/dev/null 2>&1; then
  open "$WORK_MD" >/dev/null 2>&1 || true
fi
if ! grep -q 'kandidati.php' "$WORK_MD" 2>/dev/null; then
  warn "Noch kein Codebefund in der Arbeitsdatei."
  if ! confirm "Trotzdem fortfahren?"; then
    _die "Erst Mapping (Codex oder Wizard 02), dann 03."
  fi
fi
pause "Datei gesehen?"

stage "Hauptsuche"
say "Codebefund: taegliche Suche = Kandidati Filter."
say "kandidati.php?page=list_ajax  — nicht search.php, nicht Partner-Suche."
ask_jno Q_MAIN_SEARCH "Ist das eure taegliche Kandidatensuche?"
write_env Q_MAIN_SEARCH "$Q_MAIN_SEARCH"

stage "Nebenmasken in Release 1"
say "Zusatz im Code: Partner-Namenssuche, QC-Suche, Nalog/Bot-Liste."
say "Menue-Pretraga sucht Seiten, keine Kandidaten."
ask_jno Q_R1_ONLY_MAIN "Soll Release 1 NUR die Kandidati-Filter-Suche koennen?"
write_env Q_R1_ONLY_MAIN "$Q_R1_ONLY_MAIN"

stage "Beruf in der alten Filter-UI"
say "Filter hat Struke, Schule, Smjer (Ausbildungsweg)."
say "Kein Erfahrungsberuf, keine Taetigkeitsart, kein occupation-Profil."
ask_jno Q_STRUKA_IS_AUSBILDUNG "Meint Struke/Smjer bei euch den Ausbildungsberuf?"
ask_jno Q_MCP_THREE_LAYERS "Soll der MCP drei Berufsschichten haben, obwohl die alte UI das nicht trennt?"
write_env Q_STRUKA_IS_AUSBILDUNG "$Q_STRUKA_IS_AUSBILDUNG"
write_env Q_MCP_THREE_LAYERS "$Q_MCP_THREE_LAYERS"

stage "Erfahrung / 5 Jahre"
say "Filter hat nur Checkbox Radno iskustvo = ja/nein, keine Jahreszahl."
ask Q_EXPERIENCE "Was zaehlt 5 Jahre? Akte / Lebenslauf / beide / OFFEN:"
[[ -z "$Q_EXPERIENCE" ]] && Q_EXPERIENCE="OFFEN"
write_env Q_EXPERIENCE "$Q_EXPERIENCE"

stage "Was die alte UI nicht filtert"
say "Nicht in der Hauptsuche: Stadt/Wunschort, Skills, Freitext, Berufssuchprofil."
ask_jno Q_R1_ADD_CITY "Release 1 trotzdem Ort/Wunschort?"
ask_jno Q_R1_ADD_SKILLS "Release 1 trotzdem Skills?"
ask_jno Q_R1_ADD_PROFILE "Release 1 Berufssuchprofile nutzen?"
write_env Q_R1_ADD_CITY "$Q_R1_ADD_CITY"
write_env Q_R1_ADD_SKILLS "$Q_R1_ADD_SKILLS"
write_env Q_R1_ADD_PROFILE "$Q_R1_ADD_PROFILE"

stage "Kontakte und SQL-Lesen"
say "Q4: interne Rollen sehen alle Felder inklusive Kontakt. Kunde erst spaeter."
say "Alte UI zeigt Mobilnummer in der Liste. Das widerspricht Q4 nicht."
say "Naechster Code-Schritt liest serversidedata.php inklusive Personenfelder."
say "Keine Kandidatenzeilen in Git oder Chat."
ask_jno Q_SQL_PERSON_FIELDS "SQL/PHP mit Personenfeldern lesen, ohne Datensatz-Dump: einverstanden?"
write_env Q_SQL_PERSON_FIELDS "$Q_SQL_PERSON_FIELDS"
_append_note "Abnahme gegen Codebefund" "Hauptsuche taeglich: $Q_MAIN_SEARCH
R1 nur Hauptsuche: $Q_R1_ONLY_MAIN
Struke = Ausbildung: $Q_STRUKA_IS_AUSBILDUNG
MCP drei Schichten: $Q_MCP_THREE_LAYERS
5 Jahre: $Q_EXPERIENCE
R1 Ort: $Q_R1_ADD_CITY
R1 Skills: $Q_R1_ADD_SKILLS
R1 Berufssuchprofil: $Q_R1_ADD_PROFILE
SQL Personenfelder ohne Dump: $Q_SQL_PERSON_FIELDS"

stage "Secret-Check, Git, Status"
SCAN_OUT="/private/tmp/dino-crm-wiring-scan.txt"
set +o pipefail
if command -v rg >/dev/null 2>&1; then
  rg -n -i 'password|api[_-]?key|postgres://|eyJ' "$WORK_MD" > "$SCAN_OUT" || true
else
  grep -n -i -E 'password|api[_-]?key|postgres://|eyJ' "$WORK_MD" > "$SCAN_OUT" || true
fi
set -o pipefail
SCAN_N=$(wc -l < "$SCAN_OUT" | tr -d ' ')
if [[ "$SCAN_N" != 0 ]]; then
  warn "$SCAN_N verdraechtige Zeile(n). Nicht vorlesen."
  if ! confirm "Arbeitsdatei ist ohne Secrets/PII"; then
    _die "Erst bereinigen."
  fi
else
  say "Kein Treffer im groben Netz."
fi
if git -C "$DOCS_REPO" status --short >/dev/null 2>&1; then
  git -C "$DOCS_REPO" status --short
fi
if ! confirm "Kein CRM-Code und kein Dump sind fuer das Doku-Repo staged"; then
  _die "Dateien zuerst aus dem Doku-Repo nehmen."
fi
ask WIRING_STATUS "Status (ENTWURF / PASS_WITH_GAPS / FAIL):"
write_env WIRING_STATUS "$WIRING_STATUS"
_append_note "Status" "$WIRING_STATUS"
say "Datei: $WORK_MD"
note "Bewusst offen: Ranking, Auth, Export, serversidedata-SQL, Q8.5-Formel wenn OFFEN."
pause "Enter zum Beenden."

finish
