#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Local state stays outside Git. Do not point ENV_FILE at the docs repo.
ENV_FILE="/private/tmp/dino-crm-wiring.env"
WORK_MD="/private/tmp/dino-crm-app-wiring.md"
HITS_DIR="/private/tmp/dino-crm-wiring-work"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEMPLATE_MD="$DOCS_REPO/docs/discovery/crm-app-wiring.template.md"

banner "CRM-Verdrahtung 01 · Pfad finden und Suchcode scannen"

_die() { warn "$1"; exit 1; }

_abs_dir() {
  local p="$1"
  [[ -n "$p" ]] || return 1
  [[ -d "$p" ]] || return 1
  (cd "$p" && pwd)
}

stage "Zweck und Verbote"
say "Dieser Wizard macht nur Lage, Arbeitsdatei und Suche im CRM-Quellcode."
say "Er baut keinen MCP, oeffnet keine Datenbank und schreibt nichts ins Git."
step "CRM nicht installieren, kein Docker/Compose starten."
step "OrbStack, SQL-Dump und ZIP geschlossen lassen."
step "CRM-Code nicht in das Doku-Repo kopieren."
note "Doku-Repo: $DOCS_REPO"
note "Zustand landet in $ENV_FILE"
if ! confirm "Ich installiere nichts, oeffne kein OrbStack und kopiere kein CRM ins Doku-Repo"; then
  _die "Abbruch. Ohne diese Zusage geht es nicht weiter."
fi

stage "CRM-Quellcode-Pfad"
say "Braucht einen Ordner mit Quellcode (src/app/*.php/*.cs/*.ts), keinen Dump."
step "Finder: Ordner markieren, Option/Alt und Rechtsklick: Pfad kopieren."
ask CRM_PATH "Absoluter Pfad zum CRM-Quellcode:"
CRM_PATH="${CRM_PATH%/}"
CRM_ABS=$(_abs_dir "$CRM_PATH") || _die "Ordner nicht gefunden: $CRM_PATH"
case "$CRM_ABS" in
  "$DOCS_REPO"|"$DOCS_REPO"/*)
    _die "Dieser Pfad liegt im Doku-Repo. CRM-Code muss ausserhalb bleiben."
    ;;
esac
if [[ ! -e "$CRM_ABS/.git" && ! -d "$CRM_ABS/src" && ! -d "$CRM_ABS/app" && ! -f "$CRM_ABS/composer.json" && ! -f "$CRM_ABS/package.json" ]] && ! ls "$CRM_ABS"/*.csproj >/dev/null 2>&1 && ! ls "$CRM_ABS"/*.sln >/dev/null 2>&1; then
  warn "Kein typisches Repo-Muster (git/src/app/composer/package/csproj)."
  if ! confirm "Trotzdem als Quellcode verwenden?"; then
    _die "Dann zuerst den echten Code-Ordner suchen."
  fi
fi
write_env CRM_PATH "$CRM_ABS"
write_env DOCS_REPO "$DOCS_REPO"
note "gesetzt: $CRM_ABS"

stage "Arbeitsdatei anlegen"
[[ -f "$TEMPLATE_MD" ]] || _die "Vorlage fehlt: $TEMPLATE_MD"
mkdir -p "$HITS_DIR"
if [[ -f "$WORK_MD" ]]; then
  note "Arbeitsdatei existiert schon: $WORK_MD"
  if confirm "Vorlage darueber kopieren und bisherigen Inhalt verwerfen?"; then
    cp "$TEMPLATE_MD" "$WORK_MD"
    say "Vorlage neu kopiert."
  else
    say "Bestehende Arbeitsdatei bleibt."
  fi
else
  cp "$TEMPLATE_MD" "$WORK_MD"
  say "Vorlage nach $WORK_MD kopiert."
fi
write_env WORK_MD "$WORK_MD"
write_env HITS_DIR "$HITS_DIR"
if command -v open >/dev/null 2>&1; then
  open "$WORK_MD" >/dev/null 2>&1 || warn "Editor nicht geoeffnet; Datei selbst oeffnen: $WORK_MD"
fi
step "Oben Stand auf das heutige Datum setzen. Status bleibt ENTWURF."
step "CRM-Pfad in der Datei eintragen: $CRM_ABS"
step "Datenbank in diesem Lauf: keine"
pause "Arbeitsdatei gespeichert?"

stage "Stack erkennen (nur lesen)"
say "Kein npm/composer/dotnet/docker."
CRM_STACK="OFFEN"
[[ -f "$CRM_ABS/composer.json" ]] && CRM_STACK="php"
[[ -f "$CRM_ABS/package.json" && "$CRM_STACK" == OFFEN ]] && CRM_STACK="node"
ls "$CRM_ABS"/*.csproj >/dev/null 2>&1 && CRM_STACK="dotnet"
ls "$CRM_ABS"/*.sln >/dev/null 2>&1 && CRM_STACK="dotnet"
ask CRM_STACK "Stack (Enter laesst Vorschlag):"
[[ -z "$CRM_STACK" ]] && CRM_STACK="OFFEN"
CRM_GIT_REV="unbekannt"
if git -C "$CRM_ABS" rev-parse --short HEAD >/dev/null 2>&1; then
  CRM_GIT_REV=$(git -C "$CRM_ABS" rev-parse --short HEAD)
fi
write_env CRM_STACK "$CRM_STACK"
write_env CRM_GIT_REV "$CRM_GIT_REV"
note "Stack=$CRM_STACK  git=$CRM_GIT_REV"
if [[ -f "$CRM_ABS/.env" ]]; then
  warn ".env im CRM gefunden — nicht oeffnen, nicht kopieren."
fi

stage "Suchcode scannen"
say "Schreibt Trefferpfade nach $HITS_DIR. Kein Zeilen-Deckel."
_scan() {
  local out="$1" pattern="$2"
  local n
  set +o pipefail
  if command -v rg >/dev/null 2>&1; then
    rg -n -g '!node_modules' -g '!vendor' -g '!.git' -g '!dist' -g '!*.min.js' -g '!.env' -g '!*.sql' -g '!*.sql.gz' -g '!*.map' -g '!tcpdf*' -g '!ckeditor/**' -g '!dompdf/**' -g '!Info/**' -i "$pattern" "$CRM_ABS" 2>/dev/null > "$out" || true
  else
    grep -R -n -i --exclude-dir=node_modules --exclude-dir=vendor --exclude-dir=.git --exclude-dir=dist --exclude=.env --exclude='*.min.js' --exclude='*.map' "$pattern" "$CRM_ABS" 2>/dev/null > "$out" || true
  fi
  set -o pipefail
  n=$(wc -l < "$out" | tr -d ' ')
  printf '%s' "$n"
}
HIT_RPC=$(_scan "$HITS_DIR/hits-rpc.txt" 'search_candidates(_filtered|_by_occupation)?|job_occupation_map|occupation_alias')
HIT_TABLES=$(_scan "$HITS_DIR/hits-tables.txt" 'idk_kandidati|idk_kandidat_radno_iskustvo|idk_kandidat_edukacija|idk_kandidat_jezici|idk_kandidat_vjestine')
HIT_UI=$(_scan "$HITS_DIR/hits-ui.txt" 'kandidat.*such|candidate.*search|filter.*beruf|ausbildung|erfahrung|jezik|sprache|vjestina|skill')
if [[ "$HIT_TABLES" == "200" || "$HIT_UI" == "200" ]]; then
  _die "Trefferliste hat genau 200 Zeilen. Das war der alte head -200 Deckel, kein vollstaendiges Ergebnis. Dateien in $HITS_DIR pruefen und Scan ohne Deckel wiederholen."
fi
write_env HIT_RPC_COUNT "$HIT_RPC"
write_env HIT_TABLES_COUNT "$HIT_TABLES"
write_env HIT_UI_COUNT "$HIT_UI"
say "Treffer RPC:     $HIT_RPC"
say "Treffer Tabellen: $HIT_TABLES"
say "Treffer UI:      $HIT_UI"
if [[ "$HIT_RPC" == 0 && "$HIT_TABLES" == 0 && "$HIT_UI" == 0 ]]; then
  warn "Keine Treffer. Code-Ordner pruefen oder im Finder nach Suche/Search sehen."
else
  say "Mindestens eine Liste hat Treffer — weiter geht es."
fi

stage "Ergebnis und naechster Wizard"
if command -v open >/dev/null 2>&1; then
  open "$HITS_DIR" >/dev/null 2>&1 || true
fi
step "Rohlisten liegen in $HITS_DIR — nicht ins Git."
step "Optimal als Naechstes: Codex den Pfad schicken: $CRM_ABS"
step "Oder selbst mappen: scripts/wizards/crm-wiring-02-map-search.sh"
note "Abnahme spaeter: scripts/wizards/crm-wiring-03-accept.sh"
note "Nachschlagewerk: docs/runbooks/crm-wiring-human-plan.md"
pause "Trefferordner gesehen?"

finish
