#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

ENV_FILE="/private/tmp/dino-crm-wiring.env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"

banner "CRM-Verdrahtung 02 · Masken und Felder zuordnen"

_die() { warn "$1"; exit 1; }

_need() {
  local v
  v=$(_existing "$1" || true)
  [[ -n "$v" ]] || _die "Zuerst Wizard 01 ausfuehren. Es fehlt $1 in $ENV_FILE"
  printf '%s' "$v"
}

_append_note() {
  local title="$1" body="$2"
  {
    printf '\n## Wizard-02 %s\n\n' "$title"
    printf '%s\n' "$body"
  } >> "$WORK_MD"
}

stage "Voraussetzungen"
[[ -f "$ENV_FILE" ]] || _die "Keine Zustandsdatei. Zuerst: scripts/wizards/crm-wiring-01-locate-and-scan.sh"
CRM_PATH=$(_need CRM_PATH)
WORK_MD=$(_need WORK_MD)
HITS_DIR=$(_need HITS_DIR)
HIT_RPC=$(_existing HIT_RPC_COUNT || true)
HIT_UI=$(_existing HIT_UI_COUNT || true)
[[ -d "$CRM_PATH" ]] || _die "CRM-Pfad weg: $CRM_PATH"
[[ -f "$WORK_MD" ]] || _die "Arbeitsdatei weg: $WORK_MD"
say "CRM:  $CRM_PATH"
say "Datei: $WORK_MD"
say "Treffer RPC=$HIT_RPC  UI=$HIT_UI"
if [[ "${HIT_RPC:-0}" == 0 && "${HIT_UI:-0}" == 0 ]]; then
  warn "Scan war leer. Wizard 01 wiederholen oder Datei per Finder suchen."
fi
pause "Passt das?"

if grep -q 'BELEGT DURCH QUELLCODE' "$WORK_MD" 2>/dev/null; then
  warn "Die Arbeitsdatei ist schon gemappt (Codebefund vorhanden)."
  say "Wizard 02 ist dann ueberfluessig. Nimm Wizard 03."
  if ! confirm "Trotzdem selbst neu mappen und den Befund ueberschreiben?"; then
    say "Weiter: scripts/wizards/crm-wiring-03-accept.sh"
    finish
    exit 0
  fi
fi

stage "Selbst mappen oder Codex?"
say "Optimal: Codex bekommt nur den CRM-Pfad und fuellt die Tabellen aus dem Code."
say "Dieser Wizard ist der langsamere Weg, wenn du selbst im Editor zuordnen willst."
note "Pfad zum Copieren: $CRM_PATH"
if ! confirm "Ich fuelle die Tabellen jetzt selbst im Editor"; then
  say "Gut. Naechster Schritt: Codex diesen Pfad schicken (kein Dump, kein .env)."
  say "$CRM_PATH"
  say "Wenn die Arbeitsdatei gefuellt ist: scripts/wizards/crm-wiring-03-accept.sh"
  finish
  exit 0
fi

stage "Suchmasken (Tabelle 1)"
say "Oeffne Treffer und Arbeitsdatei. Eine Zeile pro Suchoberflaeche."
if command -v open >/dev/null 2>&1; then
  open "$WORK_MD" >/dev/null 2>&1 || true
  [[ -f "$HITS_DIR/hits-ui.txt" ]] && open "$HITS_DIR/hits-ui.txt" >/dev/null 2>&1 || true
  [[ -f "$HITS_DIR/hits-rpc.txt" ]] && open "$HITS_DIR/hits-rpc.txt" >/dev/null 2>&1 || true
fi
step "Tabelle 1. Suchmasken fuellen: UI-Name, Datei, RPC, Kontakte ja/nein, Note."
step "Detailkarte eines Kandidaten ist keine Suche."
step "RPC mit E-Mail/Telefon: R1-AUSSCHLUSS, nicht wrappen."
pause "Tabelle 1 gespeichert?"
ask MAIN_SEARCH_MASK "Name der Recruiter-Hauptsuche (oder OFFEN):"
ask MAIN_SEARCH_FILE "Datei der Hauptsuche relativ zum CRM (oder OFFEN):"
write_env MAIN_SEARCH_MASK "$MAIN_SEARCH_MASK"
write_env MAIN_SEARCH_FILE "$MAIN_SEARCH_FILE"
_append_note "Suchmasken" "Hauptsuche: $MAIN_SEARCH_MASK
Datei: $MAIN_SEARCH_FILE"

stage "Feldkarte (Tabelle 2)"
say "Jedes Pflichtfeld eine Zeile. Fehlt es in der UI: 'fehlt in UI' + OFFEN."
step "Pflicht: Ausbildungsberuf, Erfahrungsberuf, Taetigkeitsart, Profil, Erfahrung, Ort, Sprache, Skill, Alter, Status, Freitext."
step "Ein Feld 'Beruf' ohne Schicht bleibt OFFEN — nicht raten."
step "Zwei Erfahrungspeicher = zwei Zeilen."
if [[ -n "$MAIN_SEARCH_FILE" && "$MAIN_SEARCH_FILE" != OFFEN && -f "$CRM_PATH/$MAIN_SEARCH_FILE" ]]; then
  if command -v open >/dev/null 2>&1; then
    open "$CRM_PATH/$MAIN_SEARCH_FILE" >/dev/null 2>&1 || true
  fi
  note "geoeffnet: $CRM_PATH/$MAIN_SEARCH_FILE"
else
  warn "Hauptsuche-Datei nicht geoeffnet. Pfad in hits-ui.txt suchen."
fi
pause "Tabelle 2 gespeichert?"
ask OCCUPATION_LAYERS "Drei Berufsschichten getrennt? (ja/nein/OFFEN):"
ask EXPERIENCE_SOURCE "Was zaehlt Dauer? (Akte/Lebenslauf/beide/OFFEN):"
write_env OCCUPATION_LAYERS "$OCCUPATION_LAYERS"
write_env EXPERIENCE_SOURCE "$EXPERIENCE_SOURCE"
_append_note "Felder" "Schichten getrennt: $OCCUPATION_LAYERS
Erfahrungsquelle: $EXPERIENCE_SOURCE"

stage "RPC-Karte (Tabelle 3)"
say "Nur Funktionsnamen und Argumenttypen, keine Personenwerte."
if command -v open >/dev/null 2>&1 && [[ -f "$HITS_DIR/hits-rpc.txt" ]]; then
  open "$HITS_DIR/hits-rpc.txt" >/dev/null 2>&1 || true
fi
step "Jede Maske auf 0..n RPCs zeigen. 0 = OFFEN."
step "crm_api.search_candidates mit Kontakt: R1-AUSSCHLUSS."
pause "Tabelle 3 gespeichert?"
ask SEARCH_RPCS "RPC-Namen kommasepariert (oder OFFEN):"
write_env SEARCH_RPCS "$SEARCH_RPCS"
_append_note "RPCs" "$SEARCH_RPCS"
say "Als Naechstes: scripts/wizards/crm-wiring-03-accept.sh"

finish
